name: Build & Release

on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        run: echo ::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}
        id: get_tag

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & Build
        run: yarn --frozen-lockfile && yarn build

      - name: Bundle
        run: |
          mkdir -p ./temp/npwd_crypto
          cp ./{LICENSE,README.md,fxmanifest.lua,config.json} ./temp/npwd_crypto
          cp -r ./dist ./temp/npwd_crypto
          cd ./temp && zip -r ../npwd_crypto_esx.zip ./npwd_crypto
          grep -rl '"framework": "esx"' ./npwd_crypto/config.json | xargs sed -i 's/"framework": "esx"/"framework": "qb"/g' 
          zip -r ../npwd_crypto_qb.zp ./npwd_crypto

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        id: auto_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: NPWD Crypto Release | ${{ steps.get_tag.outputs.VERSION_TAG }}
          prerelease: false
          files: |
            npwd_crypto_esx.zip
            npwd_crypto_qb.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}